apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: react-pipeline-example
  name: react-pipeline-example
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: react-pipeline-example
    weight: 100
